### ISSUE TITLE
getting the error for main.py file not found when running the action cirolini/genai-code-review@v2

### ISSUE THREAD

**Issue by Asthethi** [cirolini/genai-code-review#47]
Run cirolini/genai-code-review@v2
  with:
    openai_api_key: ***
    github_token: ***
    github_pr_id: [2](https://github.com/Asthethi/JavaPractice/actions/runs/9253660345/job/25453809409?pr=2#step:5:2)
    openai_model: gpt-[3](https://github.com/Asthethi/JavaPractice/actions/runs/9253660345/job/25453809409?pr=2#step:5:3).5-turbo
    mode: files
    language: java
    openai_temperature: 0.5
    openai_max_tokens: 20[4](https://github.com/Asthethi/JavaPractice/actions/runs/9253660345/job/25453809409?pr=2#step:5:4)8
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.23-9/x[6](https://github.com/Asthethi/JavaPractice/actions/runs/9253660345/job/25453809409?pr=2#step:5:6)4
/usr/bin/docker run --name bd3e9[7](https://github.com/Asthethi/JavaPractice/actions/runs/9253660345/job/25453809409?pr=2#step:5:7)b8141ed9284bb43c474[8](https://github.com/Asthethi/JavaPractice/actions/runs/9253660345/job/25453809409?pr=2#step:5:8)769_1c749f --label 066803 --workdir /github/workspace --rm -e "JAVA_HOME" -e "INPUT_OPENAI_API_KEY" -e "INPUT_GITHUB_TOKEN" -e "INPUT_GITHUB_PR_ID" -e "INPUT_OPENAI_MODEL" -e "INPUT_MODE" -e "INPUT_LANGUAGE" -e "INPUT_OPENAI_TEMPERATURE" -e "INPUT_OPENAI_MAX_TOKENS" -e "INPUT_CUSTOM_PROMPT" -e "OPENAI_API_KEY" -e "GITHUB_TOKEN" -e "GITHUB_PR_ID" -e "OPENAI_MODEL" -e "OPENAI_TEMPERATURE" -e "OPENAI_MAX_TOKENS" -e "MODE" -e "LANGUAGE" -e "CUSTOM_PROMPT" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -
python: can't open file '/github/workspace/src/main.py': [Errno 2] No such file or directory

**Comment by dokimiki** [comment]
I have the same issue. Is there any solution to this problem?

**Comment by leandromsft** [comment]
I have the same issue, any recommendation?

**Comment by dlidstrom** [comment]
Fixed and improved Readme: https://github.com/dlidstrom/genai-code-review

**Comment by Spxc** [comment]
It's throwing a not found on @3 when trying to checkout, so not sure the docs are kosher? @dlidstrom 
Should be @v3 / @v3.0.2

**Comment by dlidstrom** [comment]
Right, might need an update. Thanks

**Comment by tapegram** [comment]
@dlidstrom using the 3.0.2 (and 3.0.0) version I'm getting the error mentioned here: https://community.openai.com/t/error-with-openai-1-56-0-client-init-got-an-unexpected-keyword-argument-proxies/1040332

**Comment by dlidstrom** [comment]
@tapegram I haven’t seen this issue (yet). Would you be able to submit a PR to fix it? I will publish an updated version for everyone’s benefit.

**Comment by fredlemieux** [comment]
3.0.2 fixes the error mentioned in the `getting the error for main.py file not found` issue,

but I've got the same error as @tapegram :

```
Traceback (most recent call last):
  File "/app/src/main.py", line 246, in <module>
    main()
  File "/app/src/main.py", line 24, in main
    openai_client = OpenAIClient(env_vars['OPENAI_MODEL'],
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/clients/openai_client.py", line 28, in __init__
    self.client = OpenAI()
                  ^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_client.py", line 122, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 825, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 723, in __init__
    super().__init__(**kwargs)
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
```

I'll have a look to see if I can fix the issue and create PR.

**Comment by dlidstrom** [comment]
I just published [v3.0.3](https://github.com/marketplace/actions/chatgpt-github-actions) which contains a fix for that issue.

**Comment by fredlemieux** [comment]
Ha! I was literally just about to raise a PR to update the openai to the latest version. You beat me to it :-)

**Comment by fredlemieux** [comment]
In the example code there were some permissions missing that are required. @dlidstrom I created at PR: https://github.com/dlidstrom/genai-code-review/pull/1/

But with those permissions, it works beautifully ❤️🙌.  Will you raise a PR and merge this back into the original repo?

Personally I think being able to trigger the review from the PR chat with /review or similar would be the best approach.  I'll raise a PR for this when I've implemented it myself 👍

**Comment by keenan-repo** [comment]
@dlidstrom I was trying to use this action on our github server but since the github client always uses the default we were unable to. I've created a PR that adds an optional base url, would you be able to take a look? https://github.com/dlidstrom/genai-code-review/pull/2

**Comment by cirolini** [comment]
Fixed in **v2.1**, which is out now. `@v2` has been moved to it, so if you pin `cirolini/genai-code-review@v2` you get the fix on your next run with no workflow change.

## What was wrong

GitHub starts container actions with `--workdir /github/workspace`, which overrides the `WORKDIR /app` in the image. The entrypoint was `CMD ["python", "src/main.py"]` — relative — so it resolved against *your* checked-out repository instead of the action's own code. Hence `can't open file '/github/workspace/src/main.py'`.

It shipped and survived two years because this repository's own demo workflow ran `actions/checkout` before the action. That put a `src/main.py` on the container's working directory, so the action passed its own tests here while failing on every other repository. I've removed that checkout, and CI now builds the image and runs it with the same `--workdir` GitHub uses — so a regression fails the build instead of reaching you.

There was a second, independent break several of you hit: `openai` was pinned to `1.30.1` while `httpx` was not pinned at all, and `httpx` 0.28 removed the `proxies` argument that version passes. All dependencies are now pinned, including the transitive ones that affect startup.

## Also worth knowing

Several comments here were really about missing permissions. The workflow example never included this, and it needs to:

```yaml
permissions:
  contents: read
  pull-requests: write
```

Without `pull-requests: write` the action authenticates, reads your PR, and then silently fails to post. The README now says so. You also don't need `actions/checkout` at all — this action reads the PR over the API.

The default model changed to `gpt-5.6-luna`, because `gpt-3.5-turbo` loses API access on 2026-10-23. It costs less than `gpt-3.5-turbo` did, so the moved tag shouldn't raise anyone's bill.

## Thanks

@Asthethi for the report with the full runner log — the `--workdir` line in it is what pinned the cause down. @arjunsuresh for the fix in #50, which is what shipped, with credit on the commit. @fredlemieux for identifying the permissions problem. @tapegram and @fredlemieux for the `proxies` traceback. @keenan-repo for the GHES `base_url` work — that's on the list for v3.

And @dlidstrom, who forked this and kept it working for people while I wasn't. That was the right thing to do and I'm not going to pretend otherwise. If you're on that fork today it still works; v3 is being built here in the open, and I'll make the relationship between the two explicit in the README rather than quietly competing with it.

Sorry this took two years.
